### ISSUE TITLE
Can't access the trained model address.

### ISSUE THREAD

**Issue by ElephantGit** [antspy/inception_v1.pytorch#3]
Hi, your work is so amazing and so helpful ! But I can't access the url of trained model, could you please give me another one?

Regard!

**Comment by antspy** [comment]
Hi, 

thank you! Note though that the trained weights are not so good, with a top accuracy of only 26%. You are probably better off by training the model from scratch. 

In any case I can access the url just fine; note that it is hosted on mega.co.nz. Are you able to access that site from your country? Otherwise you might need to use a VPN
